CREATE TABLE airports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(3) NOT NULL,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX ux_airports_code ON airports (code);

CREATE TABLE aircrafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    CONSTRAINT chk_aircrafts_capacity_positive CHECK (capacity > 0)
);

CREATE TABLE flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL,
    departure_airport_id BIGINT NOT NULL,
    arrival_airport_id BIGINT NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    arrival_time TIMESTAMP NOT NULL,
    aircraft_id BIGINT NOT NULL,
    CONSTRAINT fk_flights_departure_airport
        FOREIGN KEY (departure_airport_id) REFERENCES airports (id),
    CONSTRAINT fk_flights_arrival_airport
        FOREIGN KEY (arrival_airport_id) REFERENCES airports (id),
    CONSTRAINT fk_flights_aircraft
        FOREIGN KEY (aircraft_id) REFERENCES aircrafts (id),
    CONSTRAINT chk_flights_different_airports
        CHECK (departure_airport_id <> arrival_airport_id),
    CONSTRAINT chk_flights_time_order
        CHECK (departure_time < arrival_time)
);

CREATE INDEX ix_flights_departure_airport_id
    ON flights (departure_airport_id);
CREATE INDEX ix_flights_arrival_airport_id
    ON flights (arrival_airport_id);
CREATE INDEX ix_flights_aircraft_id
    ON flights (aircraft_id);

CREATE TABLE passengers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    passport_number VARCHAR(50) NOT NULL,
    flight_id BIGINT NOT NULL,
    CONSTRAINT fk_passengers_flight
        FOREIGN KEY (flight_id) REFERENCES flights (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_passengers_passport_number
    ON passengers (passport_number);
CREATE INDEX ix_passengers_flight_id ON passengers (flight_id);
